### ISSUE TITLE
Inaccuracy in README

### ISSUE THREAD

**Issue by n16h7hunt3r** [FireDynamics/ARTSS#13]
`- '--jobs [cores]' -> How many cores should be used for compilation (default $(nproc))`

As written in `compile.sh` its the number of tasks done parallel. The number of cores used is determined by your OS. For more information take a look at `man make`.

**Comment by MaxBoehler** [comment]
f7f2538cbc13306e846662b71fb170bb2ec45a12

Done!
Thanks for the hint.

**Comment by hrkrx** [comment]
This should be reopened, since the README contains more inaccuracies:

 - Complete c++17 support is only available since gcc 7
 - Unit test seem to be missing in this repository

**Comment by MaxBoehler** [comment]
Thanks, I updated the requirement for GCC.
Unittest will be added later to the repository.

Please open a new Issue if you find any more inaccuracies.
