### ISSUE TITLE
Define code guidelines

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#15]

**Comment by n16h7hunt3r** [comment]
Already done in my fork

**Comment by LinhWuerzburger** [comment]
should be done in CONTRIBUTING.md

**Comment by LinhWuerzburger** [comment]
besides the google coding guidelines, there are a few things we should emphasise or rather add. For example where to put the asterisk of a pointer, where to put the opening brackets, no camel case but underscores etc. the justification for the rules is probably also a good thing to add.
