### ISSUE TITLE
Be able to run ARTSS on JURECA

### ISSUE THREAD

**Issue by lu-kas** [FireDynamics/ARTSS#2]

**Comment by LinhWuerzburger** [comment]
artss_gpu error message

**Comment by LinhWuerzburger** [comment]
error message gpu version

**Comment by LinhWuerzburger** [comment]
postponed until jureca has updated its pgi version (current 19.3)

**Comment by MaxBoehler** [comment]
I will try to install PGI 19.10 on JURECA

**Comment by LinhWuerzburger** [comment]
Works with PGI 19.10
