### ISSUE TITLE
Ambiguous and meaningless names of fields and functions

### ISSUE THREAD

**Issue by hrkrx** [FireDynamics/ARTSS#51]
It would be nice to have explanatory variable and function names, 
since eg. nobody immediately knows what:
```
IX
xi
yj
zk
tn
(i can go on for probably 100 more)
```
does.

Also documentation, not comments in the code, for important classes would make the work for uninitiated people much less painful.

**Comment by LinhWuerzburger** [comment]
it would be nice if you would read the explanation given at the definition of the method and there is already an issue about a missing wiki for further documentation.
