### ISSUE TITLE
create issue template

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#54]
we should create an issue template to be more specific about issues. It also makes it easier for contributors to report issues.

**Comment by LinhWuerzburger** [comment]
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by LinhWuerzburger** [comment]
https://github.com/JuPedSim/jpscore/tree/master/.github/ISSUE_TEMPLATE

**Comment by n16h7hunt3r** [comment]
Other useful points could be:

- xml file run (if non std attached)
- logout (as file attached)
- if produced vtk files
