### ISSUE TITLE
Meaning/purpose of field T_a and the function ForceSource

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#65]
T_a is only used in Function ForceSource in ISolver.cpp, which is also only used in the initialisation of the fields.

In ForceSource T_a is initialised with the values of T0 and in the Function BuoyancyForce (Functions.cpp) the fields are subtracted from each other resulting in zero (lines 371 and 377). 

ISolver.cpp
![image](https://user-images.githubusercontent.com/9675744/86916922-9621c380-c124-11ea-87bb-eb0c9114668c.png)

Functions.cpp
![image](https://user-images.githubusercontent.com/9675744/86917197-fadd1e00-c124-11ea-8739-8651587e9fef.png)

This doesn't seem correct, and if T_a is not used for the force source anymore, it can be removed. Some investigation of the purpose of the force source method is necessary.

**Comment by n16h7hunt3r** [comment]
T_a is calculated in
https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/adaption/Layers.cpp#L154
https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/adaption/Layers.cpp#L173

I'm not 100% sure whats happening in those two lines.

```data_tempA``` is an reference on

https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/adaption/Layers.cpp#L135

and ```m_Ta``` is an reference on

https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/adaption/Layers.cpp#L25

in solver


T_a is also used in
- https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/analysis/Analysis.cpp#L71 where T_a gets compared to an analytical solution (m_solution->GetT() returns T_a)
- https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/analysis/Analysis.cpp#L225 where T_a is used to calculate an error
- https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/adaption/Adaption.cpp#L117 where T_a is written to a file

where seems no other reference to be

**Comment by n16h7hunt3r** [comment]
of course T_a gets read only access in
https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/TimeIntegration.cpp#L135
https://github.com/FireDynamics/ARTSS/blob/9395ed34166397ec5dfd9dac2e57c5a11cbb8c56/src/TimeIntegration.cpp#L104

but i think those can be deleted

**Comment by LinhWuerzburger** [comment]
Is this still up-to-date? I forgot to check this issue, mb. I know that I changed something regarding the ambient field....

**Comment by ChristianVonMach** [comment]
at least the discused lines are deleted in master. i guess its fine to close. (changed in #66?)

**Comment by LinhWuerzburger** [comment]
I guess we will close it then.
