### ISSUE TITLE
Complete ReadMe

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#7]
Missing points:
- how to compile
- basic structure
- short explanation available tools/scripts

**Comment by hrkrx** [comment]
While trying to get ARTSS up and running i hit multiple roadblocks:

The minimum for c++11 is not correct as ARTSS needs c++17 support.
That also makes the minimum of PGI 17.4 wrong as it does not support c++17.

i used 19.10 but there might be earlier versions that work

**Comment by MaxBoehler** [comment]
Thanks for the info! Indeed our new C++-std is 17. I will update the readme soon.

**Comment by MaxBoehler** [comment]
e4086c40a23df2f6945489b2ab64eff73ef38877

Done

**Comment by n16h7hunt3r** [comment]
missing space in `git clonehttps://github.com/FireDynamics/ARTSS.git` in README
