### ISSUE TITLE
Logger PR: remove log files created by cmake test

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#79]
probably just a missing rm *.log in the run.sh script of every test case of cmake test

**Comment by n16h7hunt3r** [comment]
inserted following lines in all run.sh
if test was successful
```  
    rm -f *.log
    rm -f *.vtk
    ls *.dat | grep -v '_ref.dat' | xargs rm -r
```

(c7b9c0c)

should be fixed

**Comment by n16h7hunt3r** [comment]
now deleting all output files in any case. (852a76a)

**Comment by LinhWuerzburger** [comment]
I think it is okay to just assume, that the user won't have any important log files in the test directory, so we can just remove every log file regardless of when it was created. Therefore I declare the issue fixed.
