### ISSUE TITLE
Logger PR: logger as class member?

### ISSUE THREAD

**Issue by LinhWuerzburger** [FireDynamics/ARTSS#80]
For multiple classes, the logger is not a class member despite being called in non-static methods. Referring to solver classes.

**Comment by n16h7hunt3r** [comment]
made a member or renamed logger, also some minor coding style improvements (87b52ab)

**Comment by LinhWuerzburger** [comment]
was wondering what is the better choice:
every solver class has a static control function. The function is static because it doesn't access class members, but with the logger, it might be better to change it back to a non-static method. So is it better to create a new logger and the method remains static or change the method to a non-static one and use the class member logger?

**Comment by LinhWuerzburger** [comment]
won't be of concern if the classes will be rewritten. see issue #82
