### ISSUE TITLE
Update PGI docker container 

### ISSUE THREAD

**Issue by hrkrx** [FireDynamics/ARTSS#96]
Nvidia discontinued the PGI docker container due to rebranding PGI to NVHPC compiler.

Basically the name of the container changed to _https://ngc.nvidia.com/catalog/containers/nvidia:nvhpc_

see: https://forums.developer.nvidia.com/t/ngc-pgi-docker-container-unusable/158542

all docker pull commands need to be replaced with the new name

**Comment by LinhWuerzburger** [comment]
Correspondingly, the README file has to be updated too. PGI -> NVHPC

**Comment by LinhWuerzburger** [comment]
eventually the CMakeLists.txt and compile.sh files have to be rewritten as well with regard to the name change of the compiler

**Comment by hrkrx** [comment]
default gpu cuda compute compability needs to be raised to cc35, cc30 is not supported anymore by NVC++ 20.9

**Comment by ChristianVonMach** [comment]
> default gpu cuda compute compability needs to be raised to cc35, cc30 is not supported anymore by NVC++ 20.9

thx done in acd9cb2

**Comment by ChristianVonMach** [comment]
> eventually the CMakeLists.txt and compile.sh files have to be rewritten as well with regard to the name change of the compiler

old names still exists. keeping for backward compatibility.

**Comment by hrkrx** [comment]
As seen in the updated forum thread at the top, there wont be a version without llvm. So any Issues that are caused by llvm need to be addressed rather quickly.
